name: pytest-results-actions
description: Post pytest results to the workflow summary

branding:
  icon: bookmark
  color: red

runs:
  using: node16
  main: dist/index.js

inputs:
  path:
    description: |
      A list of JUnit XML files, directories containing the former, and wildcard 
      patterns to process. See @actions/glob for supported patterns.
    required: true
  fail-on-empty:
    description: Fail the workflow if no JUnit XML was found
    required: false
    default: true
