name: tests

on:
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: pytest-summary-action-dev

      - name: Run tests
        run: pytest --junit-xml=test-results.xml || true

      - name: Summarize test results
        uses: ./
        with:
          junit-xml: test-results.xml
